### ISSUE TITLE
bullet plane intersection test

### ISSUE THREAD

**Issue by nickwn** [nickwn/ProjectATOD#3]
I do not think that the current method in EntityUtils will work. [This function](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/math/Intersector.html#intersectRayBoundsFast-com.badlogic.gdx.math.collision.Ray-com.badlogic.gdx.math.collision.BoundingBox-) may be better.

**Comment by jaeeee** [comment]
solution:

```
public static Entity raycastHasHit(Vector3 pos, Vector3 direction,
        ArrayList<Entity> entity) {
    Ray ray = new Ray(pos, direction);
    for (Entity e : entity) {
        BoundingBox out = new BoundingBox();
        if (Intersector.intersectRayBoundsFast(ray,
                e.getModelInstance().model.calculateBoundingBox(out))) {
            return e;
        }
        // e.getModelInstance().model.calculateBoundingBox();
    }
    return null;
}
```

**Comment by Jaeeee** [comment]
public static Entity raycastHasHit(Vector3 pos, Vector3 direction,
			ArrayList<Entity> entity) {
		Ray ray = new Ray(pos, direction);
		for (Entity e : entity) {
			BoundingBox out = new BoundingBox();
			if (Intersector.intersectRayBoundsFast(ray,
					e.getModelInstance().model.calculateBoundingBox(out))) {
				return e;
			}
			// e.getModelInstance().model.calculateBoundingBox();
		}
		return null;
	}
